### ISSUE TITLE
authentication | Back end

### ISSUE THREAD

**Issue by kipyegonbiegon** [kipyegonbiegon/Tour-Android-App#5]

**Comment by kipyegonbiegon** [comment]
- [ ] Login https://github.com/kipyegonbiegon/Tour-Android-App/issues/6
- [ ] Check if the user exists https://github.com/kipyegonbiegon/Tour-Android-App/issues/7

**Comment by kipyegonbiegon** [comment]
- [ ] Login https://github.com/kipyegonbiegon/Tour-Android-App/issues/6
- [ ] Check if the user exists https://github.com/kipyegonbiegon/Tour-Android-App/issues/7

**Comment by kipyegonbiegon** [comment]
- [ ] Login https://github.com/kipyegonbiegon/Tour-Android-App/issues/6
- [ ] Check if the user exists https://github.com/kipyegonbiegon/Tour-Android-App/issues/7

**Comment by kipyegonbiegon** [comment]
- [ ] Login https://github.com/kipyegonbiegon/Tour-Android-App/issues/6
- [ ] Check if the user exists https://github.com/kipyegonbiegon/Tour-Android-App/issues/7

**Comment by kipyegonbiegon** [comment]
- [ ] Login https://github.com/kipyegonbiegon/Tour-Android-App/issues/6
- [ ] Check if the user exists https://github.com/kipyegonbiegon/Tour-Android-App/issues/7

**Comment by kipyegonbiegon** [comment]
- [ ] Login https://github.com/kipyegonbiegon/Tour-Android-App/issues/6
- [ ] Check if the user exists https://github.com/kipyegonbiegon/Tour-Android-App/issues/7

**Comment by kipyegonbiegon** [comment]
- [ ] Login https://github.com/kipyegonbiegon/Tour-Android-App/issues/6
- [ ] Check if the user exists https://github.com/kipyegonbiegon/Tour-Android-App/issues/7
